title: North Shore Holdings Ltd
description: "North Shore Holdings acquires, renovates, leases and manages residential real estate in the Chicagoland area."

# exclude: [public, Gemfile, Gemfile.lock, Rakefile, README.md]

permalink: /:title
markdown: rdiscount

sass:
  sass_dir: _scss
  style: :compressed