title: North Shore Holdings Ltd
author: Scott Weisman
subtitle: "A nice static website, ready for design."
description: "A nice static website, ready for design."

# exclude: [public, Gemfile, Gemfile.lock, Rakefile, README.md]

permalink: /:title
markdown: rdiscount
pygments: true
